
const CLOUD = "https://res.cloudinary.com/drezpxdjw/image/upload";

let all_product = [
  { id: 1, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/product_1.png`, new_price: 50.0, old_price: 80.5 },
  { id: 2, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/product_2.png`, new_price: 85.0, old_price: 120.5 },
  { id: 3, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/product_3.png`, new_price: 60.0, old_price: 100.5 },
  { id: 4, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/product_4.png`, new_price: 100.0, old_price: 150.0 },
  { id: 5, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/product_5.png`, new_price: 85.0, old_price: 120.5 },
  { id: 6, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/product_6.png`, new_price: 85.0, old_price: 120.5 },
  { id: 7, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/product_7.png`, new_price: 85.0, old_price: 120.5 },
  { id: 8, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/product_8.png`, new_price: 85.0, old_price: 120.5 },
  { id: 9, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/product_9.png`, new_price: 85.0, old_price: 120.5 },
  { id: 10, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/product_10.png`, new_price: 85.0, old_price: 120.5 },
  { id: 11, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/product_11.png`, new_price: 85.0, old_price: 120.5 },
  { id: 12, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/product_12.png`, new_price: 85.0, old_price: 120.5 },
  { id: 13, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/womenprod.jpg`, new_price: 85.0, old_price: 120.5 },
  { id: 14, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/womenprod1.avif`, new_price: 85.0, old_price: 120.5 },
  { id: 15, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/womenproduct3.avif`, new_price: 85.0, old_price: 120.5 },
  { id: 16, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/womenprod4.avif`, new_price: 85.0, old_price: 120.5 },
  { id: 17, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/womenprod.avif`, new_price: 85.0, old_price: 120.5 },
  { id: 18, name: "Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse", category: "women", image: `${CLOUD}/womenproduct2.avif`, new_price: 85.0, old_price: 120.5 },
  { id: 19, name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket", category: "men", image: `${CLOUD}/product_13.png`, new_price: 85.0, old_price: 120.5 },
  { id: 20, name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket", category: "men", image: `${CLOUD}/product_14.png`, new_price: 85.0, old_price: 120.5 },
  { id: 21, name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket", category: "men", image: `${CLOUD}/product_15.png`, new_price: 85.0, old_price: 120.5 },
  { id: 22, name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket", category: "men", image: `${CLOUD}/product_16.png`, new_price: 85.0, old_price: 120.5 },
  { id: 23, name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket", category: "men", image: `${CLOUD}/product_17.png`, new_price: 85.0, old_price: 120.5 },
  { id: 24, name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket", category: "men", image: `${CLOUD}/product_18.png`, new_price: 85.0, old_price: 120.5 },
  { id: 25, name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket", category: "men", image: `${CLOUD}/product_19.png`, new_price: 85.0, old_price: 120.5 },
  { id: 26, name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket", category: "men", image: `${CLOUD}/product_20.png`, new_price: 85.0, old_price: 120.5 },
  { id: 27, name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket", category: "men", image: `${CLOUD}/product_21.png`, new_price: 85.0, old_price: 120.5 },
  { id: 28, name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket", category: "men", image: `${CLOUD}/product_22.png`, new_price: 85.0, old_price: 120.5 },
  { id: 29, name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket", category: "men", image: `${CLOUD}/product_23.png`, new_price: 85.0, old_price: 120.5 },
  { id: 30, name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket", category: "men", image: `${CLOUD}/product_24.png`, new_price: 85.0, old_price: 120.5 },
  { id: 31, name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket", category: "men", image: `${CLOUD}/menprod2.avif`, new_price: 85.0, old_price: 120.5 },
  { id: 32, name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket", category: "men", image: `${CLOUD}/menprod3.avif`, new_price: 85.0, old_price: 120.5 },
  { id: 33, name: "Men Green Solid Zippered Full-Zip Slim Fit Bomber Jacket", category: "men", image: `${CLOUD}/menprod4.avif`, new_price: 85.0, old_price: 120.5 },
  { id: 34, name: "Boys Orange Colourblocked Hooded Sweatshirt", category: "kid", image: `${CLOUD}/product_25.png`, new_price: 85.0, old_price: 120.5 },
  { id: 35, name: "Boys Orange Colourblocked Hooded Sweatshirt", category: "kid", image: `${CLOUD}/product_26.png`, new_price: 85.0, old_price: 120.5 },
  { id: 36, name: "Boys Orange Colourblocked Hooded Sweatshirt", category: "kid", image: `${CLOUD}/product_27.png`, new_price: 85.0, old_price: 120.5 },
  { id: 37, name: "Boys Orange Colourblocked Hooded Sweatshirt", category: "kid", image: `${CLOUD}/product_28.png`, new_price: 85.0, old_price: 120.5 },
  { id: 38, name: "Boys Orange Colourblocked Hooded Sweatshirt", category: "kid", image: `${CLOUD}/product_29.png`, new_price: 85.0, old_price: 120.5 },
  { id: 39, name: "Boys Orange Colourblocked Hooded Sweatshirt", category: "kid", image: `${CLOUD}/product_30.png`, new_price: 85.0, old_price: 120.5 },
  { id: 40, name: "Boys Orange Colourblocked Hooded Sweatshirt", category: "kid", image: `${CLOUD}/product_31.png`, new_price: 85.0, old_price: 120.5 },
  { id: 41, name: "Boys Orange Colourblocked Hooded Sweatshirt", category: "kid", image: `${CLOUD}/product_32.png`, new_price: 85.0, old_price: 120.5 },
  { id: 42, name: "Boys Orange Colourblocked Hooded Sweatshirt", category: "kid", image: `${CLOUD}/product_33.png`, new_price: 85.0, old_price: 120.5 },
  { id: 43, name: "Boys Orange Colourblocked Hooded Sweatshirt", category: "kid", image: `${CLOUD}/product_34.png`, new_price: 85.0, old_price: 120.5 },
  { id: 44, name: "Boys Orange Colourblocked Hooded Sweatshirt", category: "kid", image: `${CLOUD}/product_35.png`, new_price: 85.0, old_price: 120.5 },
  { id: 45, name: "Boys Orange Colourblocked Hooded Sweatshirt", category: "kid", image: `${CLOUD}/product_36.png`, new_price: 85.0, old_price: 120.5 },
  { id: 46, name: "Boys Orange Colourblocked Hooded Sweatshirt", category: "kid", image: `${CLOUD}/product_36.png`, new_price: 85.0, old_price: 120.5 },
  { id: 47, name: "Boys Orange Colourblocked Hooded Sweatshirt", category: "kid", image: `${CLOUD}/product_36.png`, new_price: 85.0, old_price: 120.5 },
  { id: 48, name: "Boys Orange Colourblocked Hooded Sweatshirt", category: "kid", image: `${CLOUD}/product_36.png`, new_price: 85.0, old_price: 120.5 },
];

export default all_product;
